RustCrypto/PAKEs

spake2/src/lib.rs
spake2/src/tests.rs

`debug_struct` is built in and makes your Debug impl more consistent with others.
I noodled for a while over trying to make it also tell you which Group it's  generic over, I don't think there's a way to do it unmodified, but you can either add a Default bound to it, or just add a `name()` fn to the Group trait.

More idiomatic Debug impl

---

spake2/Cargo.toml
spake2/benches/spake2.rs
spake2/src/lib.rs
spake2/tests/mod.rs
srp/Cargo.toml
srp/src/client.rs
srp/src/groups.rs
srp/src/lib.rs
srp/src/server.rs
srp/src/tools.rs
srp/src/types.rs
srp/tests/mod.rs

@newpavlov see if you agree with these changes. The imports are simpler, and/but it requires the latest stable Rust-1.31 (released today) to compile.

update everything to the "2018 edition" of Rust

---

.travis.yml
README.md

1.31.1 is our intended MSRV (Minimum Supported Rust Version), but we probably
don't actually work there because of an insufficiently-constrained dependency
that requires 1.32.
1.32 is probably our actual MSRV, and will be the one we aim for going
forward.
refs #21

travis: exercise 1.31.1 and 1.32

---

.travis.yml

This was previously locked down at a specific version (1.31.0, much older
than the current 1.36), so we'd get consistent behavior over time. But since
we allow the rustfmt build to fail (it's in allow_failures), we don't need
this consistency so much. PR authors are expected to format their code
against the current stable rustfmt, but test it against the MSRV (currently
1.32.0).
refs #21

travis: use rust 'stable' for rustfmt check

---

spake2/Cargo.toml

This was just "1", which allowed our MSRV to be accidentally raised from 1.31
to 1.32 without a deliberate spake2 minor-version bump (dalek-1.0.x compiles
with rustc-1.31, but dalek-1.1.x required 1.32).
Hopefully by making it "1.2", our MSRV will remain at 1.32 until we
explicitly decide to take on a dependency that needs something newer.
refs #21

spake2: tighten the curve25519-dalek dependency to 1.2.x

---

srp/Cargo.toml
srp/src/client.rs
srp/src/server.rs
srp/src/types.rs

Bump digest, sha-1, and sha2 dependencies to v0.9

---

srp/src/client.rs
srp/src/lib.rs
srp/src/server.rs

This fixes a few minor typos in docstrings.

srp: fix typos in docstrings

---

srp/src/lib.rs

There is a typo in the documentation of the `srp` crate.

Fix typo over -> other

---

Cargo.lock
srp/CHANGELOG.md
srp/Cargo.toml
srp/src/lib.rs

- Use `modpow` for constant time modular exponentation ([#78])
- Rebuild library ([#79])
[#78]: https://github.com/RustCrypto/PAKEs/pull/78
[#79]: https://github.com/RustCrypto/PAKEs/pull/79

srp v0.6.0

---

Cargo.lock
spake2/Cargo.toml
spake2/src/lib.rs

This is a continuation of #33.
It bumps `curve25519-dalek` to the latest stable release and replaces the `rand` crate with the version of `rand_core` which is compatible with `curve25519-dalek`: v0.5 (which is still a version behind)

spake2: bump `curve25519-dalek` to v3.0; `rand_core` => v0.5

---

.github/workflows/spake2.yml
spake2/Cargo.toml
spake2/src/lib.rs
spake2/src/tests.rs

Still has a hard dependency on `alloc`, and with the current hard dependency on `getrandom` also limited platform support

spake2: initial `no_std` support

---

.github/workflows/spake2.yml
spake2/Cargo.toml
spake2/src/lib.rs

Makes `getrandom` an optional on-by-default feature
Adds CI for `thumbv7em-none-eabi` targets

spake2: `getrandom` feature

---

spake2/benches/spake2.rs
spake2/src/lib.rs
spake2/src/tests.rs
spake2/tests/spake2.rs

Renames the following:
- `SPAKE2` => `Spake2`
- `SPAKEErr` -> `Error`
Additionally lints for `missing_docs` and adds preliminary documentation for all types and methods which previously had none.

spake2: capitalization and doc fixes

---

Cargo.lock
spake2/CHANGELOG.md
spake2/Cargo.toml

- Initial `no_std` support ([#87])
- `getrandom` feature ([#88])
- 2021 edition upgrade; MSRV 1.56 ([#80])
- Bump `curve25519-dalek` to v3.0  ([#85])
- Replace `rand` with `rand_core` v0.5 ([#85])
- Bump `hkdf` to v0.12 ([#86])
- Bump `sha2` to v0.10 ([#86])
- Renamed `SPAKE2` => `Spake2` ([#89])
- Renamed `SPAKEErr` => `Error` ([#89])
[#80]: https://github.com/RustCrypto/PAKEs/pull/80
[#85]: https://github.com/RustCrypto/PAKEs/pull/85
[#86]: https://github.com/RustCrypto/PAKEs/pull/86
[#87]: https://github.com/RustCrypto/PAKEs/pull/87
[#88]: https://github.com/RustCrypto/PAKEs/pull/88
[#89]: https://github.com/RustCrypto/PAKEs/pull/89

spake2 v0.3.0

---

.github/workflows/security-audit.yml
.github/workflows/spake2.yml
.github/workflows/srp.yml
.github/workflows/workspace.yml

Updates the actions [`actions/checkout`](https://github.com/actions/checkout) and [`actions/cache`](https://github.com/actions/cache) to v3, their latest major release.
This should basically be backwards compatible, so I expect no breakage.

Update actions used in GitHub Actions workflows to newest version

---

Cargo.lock
srp/Cargo.toml
srp/tests/srp.rs

It's under `dev-dependencies` and used for tests.

srp: bump `rand` to v0.8

---

.github/workflows/spake2.yml
.github/workflows/srp.yml
.github/workflows/workspace.yml

Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/PAKEs/actions/runs/3585086641:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).
_(Note: There is no occurrence of `actions-rs/cargo` in the workflows, so it does not need to be …

Replace unmaintained actions-rs/toolchain action in CI workflows

---

Cargo.lock
spake2/CHANGELOG.md
spake2/Cargo.toml
spake2/LICENSE-MIT
spake2/src/lib.rs

- Move IDs to relevant `Side` enum variants ([#114])
- MSRV 1.60 ([#115])
- Bump `curve25519-dalek` to v4.0 release ([#138])
[#114]: https://github.com/RustCrypto/PAKEs/pull/114
[#115]: https://github.com/RustCrypto/PAKEs/pull/115
[#138]: https://github.com/RustCrypto/PAKEs/pull/138

spake2 v0.4.0

---

.github/workflows/aucpace.yml
.github/workflows/srp.yml
.github/workflows/workspace.yml
Cargo.lock
aucpace/Cargo.toml
aucpace/README.md
aucpace/examples/key_agreement.rs
aucpace/examples/key_agreement_no_std.rs
aucpace/examples/key_agreement_partial_aug.rs
aucpace/examples/key_agreement_strong.rs
aucpace/src/client.rs
aucpace/src/database.rs
aucpace/src/errors.rs
aucpace/src/lib.rs
aucpace/src/server.rs
aucpace/src/utils.rs
aucpace/tests/test_key_agreement.rs
aucpace/tests/test_key_agreement_partial_aug.rs
aucpace/tests/test_key_agreement_strong.rs
aucpace/tests/test_key_agreement_strong_partial_aug.rs
spake2/src/ed25519.rs
spake2/src/error.rs
spake2/src/lib.rs
spake2/tests/spake2.rs
srp/Cargo.toml
srp/README.md
srp/src/client.rs
srp/src/server.rs
srp/src/types.rs
srp/src/utils.rs

While playing around in the workspace (`SPAKE2` specifically), I noticed that there were a tonne of clippy warnings so I decided to fix them all.
~~My only concern is the silencing of `write` via `#[allow(clippy::unused_io_amount)]` - I wonder if changing all of those writes to `write_all` would produce more-than-negligible performance losses.~~ These were changed to `write_all` for correctness.
This changes the MSRV of `srp` and `aucpace` from `1.60.0` to `1.61.0` otherwise they won't build with some `const fn`s ([#93706](https://github.com/rust-lang/rust/issues/93706) was added in `1.61.0`)

Fix `clippy` warnings and bump `srp` and `aucpace` MSRV to `1.61`

---

Cargo.lock
aucpace/CHANGELOG.md
aucpace/Cargo.toml

`serde v1.0.172` and later include pre-compiled binaries which is a security hazard. So until the decision gets reverted, I believe it's worth to pin upper version of `serde`. This approach may cause issues if a different crate in someone's dependency tree will depend on a post-1.0.172 version of `serde`, but I think this issue is small enough when compared to the security concerns. Also, a number of other crates in the ecosystem follow this approach, so we are not alone.
More information and discussion about the `serde` change can be found in https://github.com/serde-rs/serde/issues/2538.

Pin upper version of serde to <1.0.172

---

Cargo.lock
aucpace/CHANGELOG.md
aucpace/Cargo.toml

In 1.0.184 `serde` was [un-blobbed](https://github.com/serde-rs/serde/releases/tag/v1.0.184). To prevent accidental pulling of the blobbed versions 1.0.184 will be used as a min version.
Relevant PR: #145

Set min version of serde to 1.0.184

---

.cargo/audit.toml
.github/workflows/workspace.yml
Cargo.lock

Ignores RUSTSEC-2023-0089 until `postcard` updates to `heapless` v0.8

Fix security audit
